"""Generate the Loop 5 Markdown summary report for Design A.

Reads all results CSVs and produces design_a_report.md synthesising findings
from all 5 loops. Also prints the report to stdout.
"""
import argparse
import json
from pathlib import Path

import pandas as pd


def _load_csv_safe(path, label):
    try:
        return pd.read_csv(path)
    except FileNotFoundError:
        print(f"  Warning: {label} not found at {path}")
        return None


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir",    required=True, help="Directory with results CSVs")
    parser.add_argument("--output",         default="design_a_report.md")
    args = parser.parse_args()

    rd = Path(args.results_dir)

    # Load all results
    summary    = _load_csv_safe(rd / "design_a_summary.csv",           "baseline summary")
    abl        = _load_csv_safe(rd / "feature_ablation_ridge.csv",     "ablation raw")
    abl_summ   = _load_csv_safe(rd / "ablation_summary.csv",           "ablation summary")
    red_summ   = _load_csv_safe(rd / "design_a_reduced_summary.csv",   "reduced summary")
    calib      = _load_csv_safe(rd / "transfer_calibration_design_a.csv", "calibration")

    lines = [
        "# Design A Report — Within-Screen Holdout",
        "",
        "> Generated by the Design A Nextflow pipeline (5-loop autonomous research).",
        "",
        "---",
        "",
        "## Loop 1 — Baseline Performance",
        "",
    ]

    if summary is not None:
        ridge = summary[summary["model"] == "ridge"].iloc[0] if "ridge" in summary["model"].values else None
        rf    = summary[summary["model"] == "rf"].iloc[0]    if "rf"    in summary["model"].values else None

        def _fmt(row, col, decimals=4):
            if row is None or col + "_mean" not in row:
                return "N/A"
            return (f"{row[col + '_mean']:.{decimals}f} "
                    f"[{row[col + '_ci_lo']:.{decimals}f}, {row[col + '_ci_hi']:.{decimals}f}]")

        lines += [
            "Performance across 25 splits (mean [95% BCa CI]):",
            "",
            "| Metric | Ridge | Random Forest |",
            "|--------|-------|---------------|",
            f"| Pearson r          | {_fmt(ridge, 'pearson')}       | {_fmt(rf, 'pearson')} |",
            f"| Spearman ρ         | {_fmt(ridge, 'spearman')}      | {_fmt(rf, 'spearman')} |",
            f"| AUROC (sensitizer) | {_fmt(ridge, 'auroc_sensitizer')} | {_fmt(rf, 'auroc_sensitizer')} |",
            f"| AUPRC (sensitizer) | {_fmt(ridge, 'auprc_sensitizer')} | {_fmt(rf, 'auprc_sensitizer')} |",
            f"| Precision@50       | {_fmt(ridge, 'precision_at_50')}  | {_fmt(rf, 'precision_at_50')} |",
            f"| Precision@100      | {_fmt(ridge, 'precision_at_100')} | {_fmt(rf, 'precision_at_100')} |",
            f"| Precision@200      | {_fmt(ridge, 'precision_at_200')} | {_fmt(rf, 'precision_at_200')} |",
            "",
        ]
    else:
        lines += ["*Baseline summary not available.*", ""]

    lines += [
        "---",
        "",
        "## Loop 2 — Feature Ablation (Ridge)",
        "",
    ]

    if abl_summ is not None:
        lines += [
            "Leave-one-out ablation: Precision@50 when each feature is dropped.",
            "",
            "| Dropped Feature | Mean Precision@50 | Δ vs Baseline | Relative Drop |",
            "|-----------------|-------------------|---------------|---------------|",
        ]
        for _, row in abl_summ.iterrows():
            delta = f"{row.get('delta_precision_at_50', float('nan')):.4f}" if pd.notna(row.get("delta_precision_at_50")) else "N/A"
            rel = f"{row.get('relative_drop', float('nan')):.3f}" if pd.notna(row.get("relative_drop")) else "N/A"
            lines.append(
                f"| {row['dropped_feature']:<47} | {row['mean_precision_at_50']:.4f} "
                f"| {delta} | {rel} |"
            )
        lines.append("")

        # Top 3 findings
        top3 = abl_summ.head(3)["dropped_feature"].tolist()
        lines += [
            f"**Top 3 most impactful features** (largest drop when removed): {', '.join(top3)}",
            "",
        ]
    else:
        lines += ["*Ablation results not available.*", ""]

    lines += [
        "---",
        "",
        "## Loop 3 — Reduced Feature Model",
        "",
    ]

    if red_summ is not None and summary is not None:
        def _delta(red_row, base_row, col):
            if red_row is None or base_row is None:
                return "N/A"
            key = col + "_mean"
            if key not in red_row or key not in base_row:
                return "N/A"
            return f"{float(red_row[key]) - float(base_row[key]):+.4f}"

        r_ridge = red_summ[red_summ["model"] == "ridge"].iloc[0] if "ridge" in red_summ["model"].values else None
        r_rf    = red_summ[red_summ["model"] == "rf"].iloc[0]    if "rf"    in red_summ["model"].values else None
        b_ridge = summary[summary["model"] == "ridge"].iloc[0]   if summary is not None and "ridge" in summary["model"].values else None
        b_rf    = summary[summary["model"] == "rf"].iloc[0]      if summary is not None and "rf"    in summary["model"].values else None

        lines += [
            "Reduced model (top features from ablation) vs full 9-feature model:",
            "",
            "| Metric | Ridge (full→reduced) | RF (full→reduced) |",
            "|--------|----------------------|-------------------|",
            f"| Δ Pearson r    | {_delta(r_ridge, b_ridge, 'pearson')} | {_delta(r_rf, b_rf, 'pearson')} |",
            f"| Δ AUROC_sens   | {_delta(r_ridge, b_ridge, 'auroc_sensitizer')} | {_delta(r_rf, b_rf, 'auroc_sensitizer')} |",
            f"| Δ Precision@50 | {_delta(r_ridge, b_ridge, 'precision_at_50')} | {_delta(r_rf, b_rf, 'precision_at_50')} |",
            "",
        ]

        # Decision: full vs reduced
        if r_ridge is not None and b_ridge is not None:
            delta_p50 = float(r_ridge.get("precision_at_50_mean", 0)) - float(b_ridge.get("precision_at_50_mean", 0))
            if abs(delta_p50) < 0.01:
                rec = "Reduced feature set performs equivalently — **recommend using reduced features** in Design B for parsimony."
            elif delta_p50 > 0:
                rec = "Reduced features outperform full set — **recommend reduced features** in Design B."
            else:
                rec = "Full 9-feature model outperforms reduced set by more than 1% P@50 — **recommend keeping all 9 features** in Design B."
        else:
            rec = "Insufficient data for feature recommendation."

        lines += [f"**Recommendation:** {rec}", ""]
    else:
        lines += ["*Reduced model results not available.*", ""]

    lines += [
        "---",
        "",
        "## Loop 4 — Transfer Calibration",
        "",
    ]

    if calib is not None:
        strat_mean = calib.groupby("stratum")["spearman_r"].mean().reset_index()
        lines += [
            "Mean Spearman ρ by stratum (across all 25 splits, RF model):",
            "",
            "| Stratum | Mean Spearman ρ |",
            "|---------|-----------------|",
        ]
        for _, row in strat_mean.iterrows():
            lines.append(f"| {row['stratum']:<30} | {row['spearman_r']:.4f} |")
        lines.append("")

        hit_rho  = float(calib[calib["stratum"] == "hit_sensitizer"]["spearman_r"].mean()) if "hit_sensitizer" in calib["stratum"].values else float("nan")
        nhit_rho = float(calib[calib["stratum"] == "non_hit"]["spearman_r"].mean())         if "non_hit"        in calib["stratum"].values else float("nan")
        if not pd.isna(hit_rho) and not pd.isna(nhit_rho):
            lines += [
                f"**Finding:** RF ranks sensitizers (ρ={hit_rho:.3f}) vs non-hits (ρ={nhit_rho:.3f}) "
                f"— {'better' if hit_rho > nhit_rho else 'worse'} within the hit stratum.",
                "",
            ]
    else:
        lines += ["*Calibration results not available.*", ""]

    lines += [
        "---",
        "",
        "## Loop 5 — Design B Readiness",
        "",
        "| Item | Status |",
        "|------|--------|",
    ]

    def status(df, name):
        return "✓" if df is not None else "✗"

    n_jsons = len(list((Path(args.results_dir).parent / "artifacts" / "metrics").glob("*.json"))) if (Path(args.results_dir).parent / "artifacts" / "metrics").exists() else "?"
    lines += [
        f"| Baseline metrics JSONs generated | {n_jsons} files |",
        f"| Feature ablation complete | {status(abl, '')} |",
        f"| Reduced model evaluated | {status(red_summ, '')} |",
        f"| Transfer calibration complete | {status(calib, '')} |",
        "",
        "**Design B recommendation:**",
        "",
    ]

    if abl_summ is not None:
        top3 = abl_summ.head(3)["dropped_feature"].tolist()
        lines.append(f"- Top features identified for Design B: {', '.join(top3)} (plus supporting features)")
    if red_summ is not None:
        lines.append("- Reduced model evaluated; see Loop 3 decision above for feature set choice.")
    if calib is not None:
        lines.append("- Screen signal is stronger for sensitizers; cross-screen transfer expected to be non-trivial.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by `summary_report.py` — Design A Nextflow pipeline.*")

    report = "\n".join(lines)
    with open(args.output, "w") as f:
        f.write(report + "\n")

    print(report)
    print(f"\nReport written to {args.output}")


if __name__ == "__main__":
    main()
