name: crispr-al
channels:
  - conda-forge
  - bioconda
dependencies:
  - python =3.11
  - pytorch
  - pip
  - uv
  - marimo
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - lightgbm
  - seaborn
  - matplotlib
  - biopython
  - anndata
  - scanpy
  - tqdm
  - joblib
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
