name: crispr-al
channels:
  - pytorch
  - conda-forge
dependencies:
  - python >=3.10,<=3.13
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - seaborn
  - matplotlib
  - biopython
  - anndata
  - scanpy
  - scvi-tools
  - cellxgene-census
  - leidenalg
  - python-igraph
  - umap-learn
  - harmonypy
  - pertpy
  - gseapy
  - tqdm
  - joblib
  - pytorch-lightning
  - torchmetrics
  - optuna
  - pysam
  - pybedtools
  - pyranges
  - pyfaidx
  - pandas-plink
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - plotly
  - altair
  - gget
  - bioservices
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip:
      - vcp-cli[all]
