"""Generate the Loop 3 Markdown summary report for Design B (cross-screen transfer).

Reads Design B results CSVs and produces design_b_report.md synthesising findings
from all 3 loops. Also prints the report to stdout.
"""
import argparse
from pathlib import Path

import pandas as pd


def _load_csv_safe(path, label):
    try:
        return pd.read_csv(path)
    except FileNotFoundError:
        print(f"  Warning: {label} not found at {path}")
        return None


def _fmt(row, col, decimals=4):
    if row is None:
        return "N/A"
    mean_key = f"{col}_mean"
    lo_key   = f"{col}_ci_lo"
    hi_key   = f"{col}_ci_hi"
    if mean_key not in row:
        return "N/A"
    if lo_key in row and pd.notna(row[lo_key]):
        return (f"{row[mean_key]:.{decimals}f} "
                f"[{row[lo_key]:.{decimals}f}, {row[hi_key]:.{decimals}f}]")
    return f"{row[mean_key]:.{decimals}f}"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", required=True, help="Directory with results CSVs")
    parser.add_argument("--output",      default="design_b_report.md")
    args = parser.parse_args()

    rd = Path(args.results_dir)

    summary    = _load_csv_safe(rd / "design_b_summary.csv",                    "Design B summary")
    calib_c2s  = _load_csv_safe(rd / "transfer_calibration_design_b_c2s.csv",   "calibration c2s")
    calib_s2c  = _load_csv_safe(rd / "transfer_calibration_design_b_s2c.csv",   "calibration s2c")

    lines = [
        "# Design B Report — Cross-Screen Transfer",
        "",
        "> Generated by the Design B Nextflow pipeline (3-loop autonomous research).",
        "> Chen 2019 ↔ Sharon 2019 venetoclax CRISPR screens.",
        "",
        "---",
        "",
        "## Loop 1 — Core Transfer Performance",
        "",
    ]

    if summary is not None:
        for direction in ["chen_to_sharon", "sharon_to_chen"]:
            dir_df = summary[summary["direction"] == direction] if "direction" in summary.columns else summary
            ridge = dir_df[dir_df["model"] == "ridge"].iloc[0] if "ridge" in dir_df["model"].values else None
            rf    = dir_df[dir_df["model"] == "rf"].iloc[0]    if "rf"    in dir_df["model"].values else None
            bl    = dir_df[dir_df["model"] == "overlap_baseline"].iloc[0] if "overlap_baseline" in dir_df["model"].values else None

            dir_label = "Chen → Sharon" if direction == "chen_to_sharon" else "Sharon → Chen"
            lines += [
                f"### {dir_label}",
                "",
                "Performance across 30 splits (mean [95% BCa CI]):",
                "",
                "| Metric | Ridge | Random Forest | Overlap Baseline |",
                "|--------|-------|---------------|-----------------|",
                f"| Pearson r          | {_fmt(ridge, 'pearson')}       | {_fmt(rf, 'pearson')}       | {_fmt(bl, 'pearson')} |",
                f"| Spearman ρ         | {_fmt(ridge, 'spearman')}      | {_fmt(rf, 'spearman')}      | {_fmt(bl, 'spearman')} |",
                f"| AUROC (sensitizer) | {_fmt(ridge, 'auroc_sensitizer')} | {_fmt(rf, 'auroc_sensitizer')} | {_fmt(bl, 'auroc_sensitizer')} |",
                f"| AUPRC (sensitizer) | {_fmt(ridge, 'auprc_sensitizer')} | {_fmt(rf, 'auprc_sensitizer')} | {_fmt(bl, 'auprc_sensitizer')} |",
                f"| Precision@50       | {_fmt(ridge, 'precision_at_50')}  | {_fmt(rf, 'precision_at_50')}  | {_fmt(bl, 'precision_at_50')} |",
                f"| Precision@100      | {_fmt(ridge, 'precision_at_100')} | {_fmt(rf, 'precision_at_100')} | {_fmt(bl, 'precision_at_100')} |",
                f"| Precision@200      | {_fmt(ridge, 'precision_at_200')} | {_fmt(rf, 'precision_at_200')} | {_fmt(bl, 'precision_at_200')} |",
                "",
            ]
    else:
        lines += ["*Design B summary not available.*", ""]

    lines += [
        "---",
        "",
        "## Loop 2 — Transfer Calibration",
        "",
    ]

    for calib, label in [(calib_c2s, "Chen → Sharon"), (calib_s2c, "Sharon → Chen")]:
        lines += [f"### {label}", ""]
        if calib is not None:
            strat_mean = calib.groupby("stratum")["spearman_r"].mean().reset_index()
            lines += [
                f"Mean Spearman ρ by stratum (across all splits, RF model):",
                "",
                "| Stratum | Mean Spearman ρ |",
                "|---------|-----------------|",
            ]
            for _, row in strat_mean.iterrows():
                lines.append(f"| {row['stratum']:<30} | {row['spearman_r']:.4f} |")
            lines.append("")

            hit_rho  = float(calib[calib["stratum"] == "hit_sensitizer"]["spearman_r"].mean()) if "hit_sensitizer" in calib["stratum"].values else float("nan")
            nhit_rho = float(calib[calib["stratum"] == "non_hit"]["spearman_r"].mean())         if "non_hit" in calib["stratum"].values else float("nan")
            if not pd.isna(hit_rho) and not pd.isna(nhit_rho):
                lines += [
                    f"**Finding:** RF ranks sensitizers (ρ={hit_rho:.3f}) vs non-hits "
                    f"(ρ={nhit_rho:.3f}) — "
                    f"{'better' if hit_rho > nhit_rho else 'worse'} within the hit stratum.",
                    "",
                ]
        else:
            lines += [f"*Calibration results for {label} not available.*", ""]

    lines += [
        "---",
        "",
        "## Loop 3 — Summary & Conclusions",
        "",
    ]

    if summary is not None:
        lines += [
            "### Asymmetry in transfer performance",
            "",
        ]
        for direction in ["chen_to_sharon", "sharon_to_chen"]:
            dir_df = summary[summary["direction"] == direction] if "direction" in summary.columns else summary
            ridge = dir_df[dir_df["model"] == "ridge"].iloc[0] if "ridge" in dir_df["model"].values else None
            if ridge is not None and "precision_at_50_mean" in ridge:
                p50 = ridge["precision_at_50_mean"]
                dir_label = "Chen→Sharon" if direction == "chen_to_sharon" else "Sharon→Chen"
                lines.append(f"- {dir_label}: Ridge P@50 = {p50:.4f}")
        lines.append("")

    lines += [
        "### Feature set used",
        "",
        "- Optimised by Phase A sweep (`optimize_design_b.py`): `coess_only` "
        "(coessential_mean_r_top50, coessential_molm13_chronos)",
        "- 139 Sharon-only genes zero-imputed in feature matrix",
        "",
        "---",
        "",
        "*Report generated by `summary_report_b.py` — Design B Nextflow pipeline.*",
    ]

    report = "\n".join(lines)
    with open(args.output, "w") as f:
        f.write(report + "\n")

    print(report)
    print(f"\nReport written to {args.output}")


if __name__ == "__main__":
    main()
